name: 'setup-node'
description: 'setup-node.'
inputs:
  node-version:  
    required: true
runs:
  using: "composite"
  steps:
    uses: actions/setup-node@v2
    with:
        node-version: ${{ inputs.node-version }}
