name: 'UploadArtifact'
description: 'UploadArtifact.'
inputs:
  artifactName: 
     required: 'true'
     type: string
  artifactPath: 
     required: true 
     type: string
runs:
  using: "composite"
  steps:
   - uses: actions/upload-artifact@v2
     with:
      artifactName: ${{ inputs.artifactName }}
      artifactPath: ${{ inputs.artifactPath }}
