name: 'UploadArtifact'
description: 'UploadArtifact.'
inputs:
  name: 
   required: 'true'
   type: string
  path: 
   required: true 
   type: string
runs:
  using: "composite"
  steps:
   - uses: actions/upload-artifact@v2
     with:
      name: ${{ inputs.name }}
      path: ${{ inputs.path }}
