name: 'DownloadArtifact'
description: 'DownloadArtifact.'
inputs:
   artifactName: 
     required: true
    artifactPath: 
     required: true  
runs:
  using: "composite"
  steps:
   - uses: actions/download-artifact@v3
     with:
      artifactName: ${{ inputs.artifactName }}
      artifactPath: ${{ inputs.artifactPath }}
