name: 'DownloadArtifact'
description: 'DownloadArtifact.'
inputs:
  name: 
   required: 'true'
   type: string
  path: 
   required: true 
   type: string
runs:
  using: "composite"
  steps:
   - uses: actions/download-artifact@v3
     with:
      name: ${{ inputs.name }}
      path: ${{ inputs.path }}
