name: 'setup-node'
description: 'setup-node.'
inputs:
   nodeversion: 
     required: true
runs:
  using: "composite"
  steps:
   - uses: actions/setup-node@v2
     with:
      node-version: ${{ inputs.nodeversion }}
