# action.yaml
name: 'Blog Custom Github Action'
description: 'Call an API and get the result'
inputs:
  pokemon_id:
    description: 'number of the pokemon in the pokedex'
    required: true
    default: 1
outputs:
  pokemon_name:
    description: 'Name des Pokemons'
    default: 2
runs:
  using: "composite"
  steps:
    - run: |
       echo ${{ inputs.pokemon_name}}
      shell: bash 
